#!/usr/bin/env bash

# this is a simple config for herbstluftwm

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#5A8E3A'

# remove all existing keybindings
hc keyunbind --all

# pkill on void(runit), could use killall on others
# pkill xcompmgr
# pkill picom
# pkill pulseaudio

# ./polybar-tags &
pulseaudio --start
nvidia-settings --assign CurrentMetaMode="nvidia-auto-select +0+0 { ForceFullCompositionPipeline = On }"
# # pulseaudio
picom --backend glx --config "/home/tommitah/.config/picom/picom-wacky.conf" &
# # picom --config "/home/tommitah/.config/picom/picom-wacky.conf" &
# xcompmgr -cCfF &
# nitrogen --restore &
~/.fehbg &

# keybindings
# if you have a super key you will be much happier with Mod set to Mod4
# Mod=Mod1    # Use alt as the main modifier
Mod=Mod4   # Use the super key as the main modifier
TERMINAL=wezterm
# TERMINAL=kitty

hc keybind $Mod-Control-q quit
hc keybind $Mod-Control-r reload
hc keybind $Mod-q close
# hc keybind $Mod-Return spawn "st" # use your $TERMINAL with xterm as fallback
# hc keybind $Mod-Return spawn "alacritty" # use your $TERMINAL with xterm as fallback
hc keybind $Mod-Return spawn $TERMINAL # use your $TERMINAL with xterm as fallback
# hc keybind $Mod-Return spawn "kitty --single-instance" # use your $TERMINAL with xterm as fallback
# hc keybind $Mod-Return spawn "kitty" # use your $TERMINAL with xterm as fallback
# hc keybind $Mod-Shift-Return spawn scratchpad
# hc keybind $Mod-p spawn rofi -show drun -show-icons
hc keybind $Mod-p spawn $HOME/.config/rofi/launchers/type-1/launcher.sh
hc keybind $Mod-Shift-p spawn $HOME/.config/rofi/powermenu/type-2/powermenu.sh
# hc keybind $Mod-Shift-p spawn ./powermenu.sh
# hc keybind $Mod-p spawn dmenu_run -b -i -l 6 -p 'blast:' -fn 'JetBrainsMono Nerd Font:size=16' -nb '#1F1F28' -sb '#C8C093' -sf '#1F1F28'
# hc keybind $Mod-p spawn dmenu_run -b -i -l 6 -p 'blast:' -fn 'Iosevka:size=16' -nb '#1F1F28' -sb '#C8C093' -sf '#1F1F28'
# hc keybind $Mod-p spawn dmenu_run -b -i -l 6 -p 'blast:' -fn 'hermit:size=16' -nb '#000000' -sb '#C8C093' -sf '#1F1F28'
# hc keybind $Mod-Shift-p spawn dmenu_run -b -x 1000 -y 500 -z 700 -l 10 -p 'blast:' -fn 'Iosevka:size=18' -sb '#C8C093' -sf '#1F1F28'
# hc keybind $Mod-Shift-p spawn /home/tommitah/scripts/opensite.sh
hc keybind $Mod-Control-a spawn setxkbmap -layout us
hc keybind $Mod-Control-s spawn setxkbmap -layout fi
# hc keybind $Mod-e spawn /home/tommitah/git-repos/neovide/target/release/neovide .
hc keybind $Mod-e spawn pulseaudio-equalizer-gtk
hc keybind $Mod-Shift-e spawn pavucontrol
hc keybind $Mod-b spawn firefox
hc keybind $Mod-d spawn Discord
hc keybind $Mod-y spawn spotify
hc keybind $Mod-n spawn playerctl next
hc keybind $Mod-Shift-n spawn playerctl previous

# basic movement in tiling and floating mode
# focusing clients
# hc keybind $Mod-Left  focus left
# hc keybind $Mod-Down  focus down
# hc keybind $Mod-Up    focus up
# hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients in tiling and floating mode
# hc keybind $Mod-Shift-Left  shift left
# hc keybind $Mod-Shift-Down  shift down
# hc keybind $Mod-Shift-Up    shift up
# hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# splitting frames
# create an empty frame at the specified direction
hc keybind $Mod-v       split   bottom  0.5
hc keybind $Mod-s       split   right   0.5
# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames and floating clients
resizestep=0.02
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
# hc keybind $Mod-Control-Left    resize left +$resizestep
# hc keybind $Mod-Control-Down    resize down +$resizestep
# hc keybind $Mod-Control-Up      resize up +$resizestep
# hc keybind $Mod-Control-Right   resize right +$resizestep

# tags
# Default frame layouts have to be set before the tags are created!
hc set default_frame_layout 2
hc load '(clients max:0)'

# icon-0 = ''
# icon-1 = ''
# icon-2 = ''
# icon-3 = ''
# icon-4 = ''
# hc attr tags.by-name.custom_format %n
tag_names=( {1..5} )
# hc attr tags.by-name.1.custom_format "%{A1:herbstclient use 1:}%{A}"
# hc attr tags.by-name.2.custom_format "%{A1:herbstclient use 2:}%{A}"
# hc attr tags.by-name.3.custom_format "%{A1:herbstclient use 3:}%{A}"
# hc attr tags.by-name.4.custom_format "%{A1:herbstclient use 4:}%{A}"
# hc attr tags.by-name.5.custom_format "%{A1:herbstclient use 5:}%{A}"
# tag_names=("" "" "" "" "")
# tag_names=(" steam" " term" " web" " elec" " whats")
tag_keys=( {1..5} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if [ -n "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
# hc keybind $Mod-period use_index +1 --skip-visible
# hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
# this one changes the layout of the whole tag to floating
# hc keybind $Mod-f floating toggle
hc keybind $Mod-f attr clients.focus.floating toggle
hc keybind $Mod-m fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-d set_attr clients.focus.decorated toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jumpto last-minimized
hc keybind $Mod-o pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
# hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-g cycle
hc keybind $Mod-Shift-g cycle -1
hc keybind $Mod-i jumpto urgent

# theme
# default frame layout stacked!
# hc set_attr settings.default_frame_layout max
# hc set default_frame_layout max
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222cc'
hc set frame_border_normal_color '#101010cc'
# hc set frame_bg_normal_color '#565656aa'
hc set frame_bg_normal_color '#b0c4ac'
# hc set frame_bg_active_color '#345F0Caa'
# hc set frame_bg_active_color '#b39239' #This is very yellow
# hc set frame_bg_active_color '#C8C093' 
# hc set frame_bg_active_color '#447c5c' 
# hc set frame_bg_active_color '#191724' 
hc set frame_bg_active_color '#1d2021' 
hc set frame_border_width 0
hc set always_show_frame off
hc set frame_bg_transparent on
hc set frame_transparent_width 5
# hc set frame_gap 20
hc set frame_gap 0

# hc attr theme.title_height 15
hc attr theme.title_height 25
hc attr theme.title_when multiple_tabs
# hc attr theme.title_font 'JetBrainsMono Nerd Font:pixelsize=14'  # example using Xft
# hc attr theme.title_font 'terminus:pixelsize=14'  # example using Xft
hc attr theme.title_font 'Iosevka:pixelsize=16'  # example using Xft
# hc attr theme.title_font 'hermit:pixelsize=14'  # example using Xft
# hc attr theme.title_font '-*-fixed-medium-r-*-*-13-*-*-*-*-*-*-*'
hc attr theme.title_depth 10  # space below the title's baseline
# hc attr theme.active.color '#345F0Cef'
# hc attr theme.active.color '#b39239' # This is very yellow!
# hc attr theme.active.color '#C8C093' # This is old timey white
# hc attr theme.active.color '#447c5c' # This is old timey white
hc attr theme.active.color '#002129'
# hc attr theme.active.color '#0d0c12'
# hc attr theme.title_color '#ffffff'
hc attr theme.title_color '#C8C093'
# hc attr theme.normal.color '#191724'
# hc attr theme.normal.color '#282828'
hc attr theme.normal.color '#073642'
hc attr theme.urgent.color '#7811A1dd'
# hc attr theme.tab_color '#191724'
# hc attr theme.tab_color '#657b83'
# hc attr theme.active.tab_color '#191724'
# hc attr theme.active.tab_color '#1d2021'
hc attr theme.active.tab_color '#073642'
hc attr theme.active.tab_outer_color '#6C8257dd'
# hc attr theme.active.tab_outer_color '#b39239'
hc attr theme.active.tab_title_color '#ffffff'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 5
# hc attr theme.border_width 2
hc attr theme.floating.border_width 4
hc attr theme.floating.outer_width 1
hc attr theme.floating.outer_color black
# hc attr theme.active.inner_color '#789161'
# hc attr theme.active.inner_color '#191724'
hc attr theme.active.inner_color '#1d2021'
hc attr theme.urgent.inner_color '#9A65B0'
hc attr theme.normal.inner_color '#1d2021'
# copy inner color to outer_color
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc attr theme.tiling.outer_width 0
hc attr theme.background_color '#141414'

hc set window_gap 0
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings on
hc set mouse_recenter_gap 0
hc set snap_gap 10

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally focus new clients
hc rule floatplacement=smart
hc rule class='Thunar' floating=on
#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
#hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' floating=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off
hc rule fixedsize floating=on

hc set tree_style '╾│ ├└╼─┐'


# unlock, just to be sure
hc unlock

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

xrandr --output DP-2 --mode 2560x1440 --rate 120 &

if ! pgrep "polybar" > /dev/null 2>&1 ; then
	~/.config/polybar/launch.sh &
fi

# find the panel
# panel=~/.config/herbstluftwm/panel.sh
# [ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
# for monitor in $(hc list_monitors | cut -d: -f1) ; do
#     # start it on each monitor
#     "$panel" "$monitor" &
# done
